/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  dergiSidebar: [{type: 'autogenerated', dirName: '.'}],
  ozgedirikkitabiSidebar: [{type:'autogenerated', dirName: 'ozgedirikkitabi'}],
  pdfdosyalariSidebar: [{type:'autogenerated', dirName: 'pdfdosyalari'}],
  
     sayiOnBir8Sidebar: [
    {
      type: 'category',
      label: 'özge dir/ik¹’in bütün şiirleri’ne başlangıç denemesi²',
      items: [
        'dergi/sayi-on-bir/8',
        {
          type: 'category',
          label: "özge dirik'in bütün şiirleri",
          items: [
            'dergi/sayi-on-bir/sub8/8_1',
            'dergi/sayi-on-bir/sub8/8_2',
            'dergi/sayi-on-bir/sub8/8_3',
            'dergi/sayi-on-bir/sub8/8_4',
            'dergi/sayi-on-bir/sub8/8_5',
            'dergi/sayi-on-bir/sub8/8_6',
            'dergi/sayi-on-bir/sub8/8_7',
            'dergi/sayi-on-bir/sub8/8_8',
            'dergi/sayi-on-bir/sub8/8_9',
            'dergi/sayi-on-bir/sub8/8_10',
            'dergi/sayi-on-bir/sub8/8_11',
            'dergi/sayi-on-bir/sub8/8_12',
            'dergi/sayi-on-bir/sub8/8_13',
            'dergi/sayi-on-bir/sub8/8_14',
            'dergi/sayi-on-bir/sub8/8_15',
            'dergi/sayi-on-bir/sub8/8_16',
            'dergi/sayi-on-bir/sub8/8_17',
            'dergi/sayi-on-bir/sub8/8_18',
            'dergi/sayi-on-bir/sub8/8_19',
            'dergi/sayi-on-bir/sub8/8_20',
            'dergi/sayi-on-bir/sub8/8_21',
          ],
        },
      ],
    },
  ],
   // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
